"""Tool: Draft a postmortem from incident context."""

from datetime import datetime
from typing import Any

from app.agent.tools.base import BaseTool


class DraftPostmortemTool(BaseTool):
    """Generate a structured postmortem from incident context."""

    name = "draft_postmortem"
    description = (
        "Generate a structured postmortem document from the current incident context. "
        "Uses the conversation history, search results, and tool outputs to create "
        "a comprehensive postmortem with timeline, root cause, impact, and action items. "
        "All claims must be cited from retrieved knowledge."
    )
    schema = {
        "type": "object",
        "properties": {
            "incident_summary": {
                "type": "string",
                "description": "Brief summary of what happened",
            },
            "timeline": {
                "type": "string",
                "description": "Chronological sequence of events",
            },
            "root_cause": {
                "type": "string",
                "description": "Identified root cause",
            },
            "impact": {
                "type": "string",
                "description": "User/business impact description",
            },
            "resolution": {
                "type": "string",
                "description": "How the incident was resolved",
            },
            "action_items": {
                "type": "array",
                "items": {"type": "string"},
                "description": "Preventive action items",
            },
            "citations": {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                        "chunk_id": {"type": "string"},
                        "document_id": {"type": "string"},
                        "text": {"type": "string"},
                    },
                    "required": ["chunk_id", "document_id", "text"],
                },
                "description": "Citations from knowledge base supporting claims",
            },
        },
        "required": ["incident_summary", "timeline", "root_cause", "impact", "resolution", "action_items"],
    }

    async def execute(
        self,
        incident_summary: str,
        timeline: str,
        root_cause: str,
        impact: str,
        resolution: str,
        action_items: list[str],
        citations: list[dict[str, str]] = None,
    ) -> dict[str, Any]:
        """Generate postmortem markdown."""
        citations = citations or []

        # Format citations
        citation_text = ""
        if citations:
            citation_text = "\n\n## Citations\n"
            for i, c in enumerate(citations, 1):
                citation_text += f"[{i}] {c.get('text', '')[:200]}... (chunk: {c['chunk_id'][:8]}, doc: {c['document_id'][:8]})\n"

        postmortem = f"""# Postmortem: {incident_summary}

**Status:** Draft
**Date:** {{datetime.now().strftime('%Y-%m-%d')}}

## Summary
{incident_summary}

## Timeline
{timeline}

## Root Cause
{root_cause}

## Impact
{impact}

## Resolution
{resolution}

## Action Items
{chr(10).join(f'- [ ] {item}' for item in action_items)}

## Lessons Learned
- What went well:
- What went wrong:
- Where we got lucky:

{citation_text}

---
*Generated by On-Call Copilot. Review and finalize before publishing.*
"""

        return {
            "postmortem": postmortem,
            "citations_used": len(citations),
        }